### ISSUE TITLE
How to implement InvisibleRecaptcha

### ISSUE THREAD

**Issue by dan-pascu** [vhessam/laravel-blog-package#11]
Hi,

Can you tell me how I can implement an Invisible reCaptcha. I'm using this package https://github.com/albertcht/invisible-recaptcha and It will be nice to have the same captcha mechanism on the whole website.

Thank you.

**Comment by vhessam** [comment]
Hi @dan-pascu,
I added this feature to my to-do list.
Thanks for your consideration.

**Comment by vhessam** [comment]
Hi @dan-pascu,
I added this feature to my to-do list.
Thanks for your consideration.

I'll inform you.

**Comment by dan-pascu** [comment]
Thank you @vhessam . Looking forward for this. You did a wonderful job with this package 👍

**Comment by vhessam** [comment]
@dan-pascu sure, am happy for your feedback.
