### ISSUE TITLE
Image title can be added when create/edit a post

### ISSUE THREAD

**Issue by tzulinho** [vhessam/laravel-blog-package#2]
Hi @vhessam ,

I would like to suggest two functions:
(1) Adding a function which image title can be added when create/edit a post at the same time.
      If I create a post with an image, then the image would become "Untitled Photo", and it can not be edited.
(2) Adding a function which image can also be deleted in imageupload/index.blade.php.

Thank you very much! :-)

**Comment by vhessam** [comment]
Hi @tzulinho,
yes why not, good idea. I add it to my to do list. 

Thanks for your feedback ;)
