### ISSUE TITLE
Issue during setup 

### ISSUE THREAD

**Issue by Naveedali1234** [vhessam/laravel-blog-package#22]
Hi :)

thank you for the amazing package. 

i am trying to install it. After accessing the url **/blog_admin/setup** and making the English language as default language and clicking on setup package button, i am getting the following error:

`SQLSTATE[42703]: Undefined column: 7 ERROR: column "id" does not exist LINE 1: ...ed_at", "created_at") values ($1, $2, $3, $4) returning "id" ^ (SQL: insert into "hessam_configurations" ("key", "value", "updated_at", "created_at") values (INITIAL_SETUP, 1, 2021-01-21 08:17:56, 2021-01-21 08:17:56) returning "id")`

**Comment by vhessam** [comment]
Hi @Naveedali1234 ,
We will check this issue soon and you will be notified.
thanks for reporting

**Comment by Naveedali1234** [comment]
i am trying to use it in my application these days, if you can help me out in it, i will really appreciate it. 

thank you

**Comment by Naveedali1234** [comment]
for your information, i am using pgsql for manipulation of database.

**Comment by vhessam** [comment]
@Naveedali1234 sure.

That's it. Postgresql uses 'id' column as primary key by default. We must point that the primary key in "HessamConfiguration" model is "key".

Let me fix it soon

**Comment by Naveedali1234** [comment]
thank you for it. Also, i am just curios if i may need to customize code of the controllers, can i do it in my application or should i access the package source code for that? i am sorry if this question is out of scope of this issue, but i can get clarification on it, that would be much appreciated.

**Comment by vhessam** [comment]
I've just released the new version. Let's update the package to v.9.0.16 version and let me know if the issue persists.

**Comment by Naveedali1234** [comment]
i will check it in a while.

**Comment by vhessam** [comment]
@Naveedali1234 no problem.
You can have your own controllers if your logic is out of the package. But if you want to change the blog logic behavior you must change the package code itself. Also, if your logic fits our package you can send a pull request to update this package directly and to be one of the contributors.

Thanks Naveed

**Comment by Naveedali1234** [comment]
yes it worked. thanks alot.
